<a href="https://colab.research.google.com/github/MinaEnayat/Pytorch/blob/main/Pytorch_Intro_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors**

1.  A torch tensor is a multidimensional matrix containing elements of a single data type.
2. Similar to Numpy Array, but better on GPU's
3. Default data type float32
4. More suitable for deep learning


In [8]:
import torch
import numpy as np

# **Lists**

In [9]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [10]:
my_list = [[1,2,3,4], [1,2,3,4]]
my_list

[[1, 2, 3, 4], [1, 2, 3, 4]]

# **Numpy Arrays**

In [11]:
np1 = np.random.rand(3,4)
np1

array([[0.55685938, 0.23979901, 0.55215212, 0.83541516],
       [0.35283974, 0.46892085, 0.75863187, 0.11652463],
       [0.52628573, 0.83759102, 0.05487712, 0.46508977]])

In [12]:
np1.dtype

dtype('float64')

# **Tensors**

In [14]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.2283,  1.0935, -0.3237,  0.1402],
        [ 0.6212,  1.7475,  0.0731,  1.4457],
        [-0.3448, -0.1688,  2.3861, -0.2764]])

In [15]:
tensor_3d = torch.zeros(3,4,6)
tensor_3d

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [16]:
# Create tensors out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5569, 0.2398, 0.5522, 0.8354],
        [0.3528, 0.4689, 0.7586, 0.1165],
        [0.5263, 0.8376, 0.0549, 0.4651]], dtype=torch.float64)